Repository covidcanidoit/covidcanidoit, pull requests merged in 2020-10, with the labels that each got.

#281 Fix: Search and Country Placement in Hamburger Menu
  src/App.vue
Labels: Hacktoberfest, design, good first issue

#268 Embeddable Webpage [#259]
  public/embed-demo.html
  src/App.vue
  src/components/RiskDescription.vue
  src/store/index.js
  src/views/SearchResults.vue
Labels: enhancement

#283 Fixed padding at "You are at"
  src/components/SearchResults.vue
Labels: Hacktoberfest, design

#284 Fixed Highlight Active Page in Hamburger Menu
  src/App.vue
Labels: Hacktoberfest, design
